### ISSUE TITLE
some minor issues in the doc

### ISSUE THREAD

**Issue by ifendo** [mlverse/mall#32]
hi, thank you very much for making this available. 

While navigating through the documentation, I noticed a few minor issues:

1. I think it should be something like: `The prompt that is used will depend on`

![image](https://github.com/user-attachments/assets/91e3e909-17c5-4dfa-9d4f-9f9773c37d76)

2. it should be something like: `we want to find new ways...`
<img width="632" alt="image" src="https://github.com/user-attachments/assets/15946cbf-e1c5-49d9-833d-f18822b28eac">

3. `Classify` section is included twice:
<img width="213" alt="image" src="https://github.com/user-attachments/assets/cb8dbc62-2e70-4928-9d4c-902ea80a80ae">

Again, thank you very much.

**Comment by edgararuiz** [comment]
Thanks!
